FROM nordesbellnet/darknet:gpu-cc75-0.2

RUN apt-get update \
      && apt-get install -y curl wget \
      && rm -rf /var/lib/apt/lists/*

RUN wget https://go.dev/dl/go1.18.1.linux-amd64.tar.gz \
        && rm -rf /usr/local/go \
        && tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz \
        && rm -f go1.18.1.linux-amd64.tar.gz

ENV PATH="${PATH}:/usr/local/go/bin"
