name: build-and-push-go
on:
  workflow_dispatch:
jobs:
  build_image_and_push_to_registry:
    name: Build Docker image and push it to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push it to Docker Hub
        run: |
          chmod +x ./build_push_go.sh
          ./build_push_go.sh
